# Generated by Django 5.0.3 on 2024-03-27 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
