# Generated by Django 5.0.3 on 2024-04-03 08:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_discount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderdetails',
            options={'verbose_name': 'order details', 'verbose_name_plural': 'order details'},
        ),
        migrations.AddField(
            model_name='book',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to='static/qr'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
    ]
