# Generated by Django 5.0.4 on 2024-04-27 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_orderdetails_options_book_qr_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='data/qr_codes'),
        ),
    ]
